POST https://id.twitch.tv/oauth2/token
Content-Type: application/x-www-form-urlencoded

client_id=pl2hu83toh8d6havf73susul1lqdri&client_secret=dxdqchz4bve6mgyyttb0mr92a7npf6&grant_type=client_credentials